import { SectionsConfigType } from "@/types/configTypes";

export const SectionsConfig : SectionsConfigType[] = [
    { id: 1, activate: true },
    { id: 2, activate: true },
    { id: 3, activate: false },
    { id: 4, activate: true },
    { id: 5, activate: true },
    { id: 6, activate: false },
    { id: 7, activate: false },
    { id: 8, activate: true },
    { id: 9, activate: true },
    { id: 10, activate: true },
    { id: 11, activate: true },
    { id: 12, activate: true },
    { id: 13, activate: true },
    { id: 14, activate: true },
    { id: 15, activate: true },
    { id: 16, activate: true },
    { id: 17, activate: true },
    { id: 18, activate: true },
    { id: 19, activate: true },
    { id: 20, activate: true },
    { id: 21, activate: false },
    { id: 22, activate: true },
    { id: 23, activate: true },
    { id: 24, activate: false },
    { id: 25, activate: false },
    { id: 26, activate: false },
    { id: 27, activate: false },
    { id: 28, activate: false },
    { id: 29, activate: true },
]